development:
  adapter: postgresql
  encoding: unicode
  database: bang_development_2
  pool: 5
  username: sharpei
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: bang_test
  pool: 5
  username: sharpei
  password:
